Add search & replace feature - MOD-836
collective/collective.documentgenerator pull request #38
Opened 2021-02-11 08:08 UTC by duchenean

2021-04-19 14:52 UTC, duchenean commented on src/collective/documentgenerator/search_replace/utils.py
> +                new_odf.writestr('content.xml', newcontent)
This cause issues when writing in the zip file.

2021-04-27 09:29 UTC, gbastien requested changes
Bonjour @duchenean @sdelcourt 

çà me semble pas mal du tout, mais pour la recherche via l'interface, simplifier le "Preview" et prendre en compte "regex" serait top + compléter README pour expliquer comment faire les usecases les plus courants que nous allons avoir (replace, replace mais avec match autre valeur before/after)

Merci!

Gauthier

2021-04-27 09:29 UTC, gbastien commented on src/collective/documentgenerator/content/vocabulary.py
> +class AllPODTemplateFactory(object):
Apparemment ce n'était pas le premier dans le fichier, mais pour moi il faut le terme "Vocab" dans le class_name, c'est un VocabularyFactory, une Factory çà donne l'impression que c'est pour créer "toutes les pod templates"...  Renommer en AllPodTemplateVocabulary ou AllPodTemplateVocabFactory ou qqch du genre?

2021-04-27 09:29 UTC, gbastien commented on src/collective/documentgenerator/content/vocabulary.py
> +    def _renderTermTitle(self, brain):
to snake_case?

2021-04-27 09:29 UTC, gbastien commented on src/collective/documentgenerator/search_replace/searchreplace_panel.pt
> +                <tal:block repeat="result python:template[1]">
Lors d'un "Preview" ou d'un "Lancer", avoir le même résultat affiché (before/after)

2021-04-27 12:05 UTC, gbastien commented on src/collective/documentgenerator/search_replace/utils.py
> +        # the two xml tags we want to browse are 'office:annotation' and 'text:text-input', since its the only place
Il faudrait gérer aussi les balises text:change-start/text:change-end qui correspondent à la fonctionnalité "Suivi des modifications" et qui permet de gérer des instructions pod aussi...

2021-04-28 10:07 UTC, gbastien commented on src/collective/documentgenerator/search_replace/utils.py
> +    def __init__(self, find_expr, filenames_expr, replace, target_dir=None, ignorecase=False, recursive=False, silent=True, backup=True):
Sky is the limit?
Je suis contre la limite à 80 caractères, par contre la limite à 120 caractères je trouve çà qd même utile ;-)

2021-05-27 05:53 UTC, merged