Add force output title param for PersistentDocumentGenerationView
collective/collective.documentgenerator pull request #39
Opened 2021-02-12 09:14 UTC by jjaumotte

2021-02-12 21:48 UTC, odelaere requested changes
Nice work :)

2021-02-12 21:48 UTC, odelaere commented on src/collective/documentgenerator/tests/test_generation_view.py
> +
I think it should be integrated into `test_persistent_document_generation_call`

2021-02-22 12:34 UTC, odelaere approved these changes

2021-02-22 13:27 UTC, sdelcourt reviewed
all good

2021-02-22 13:28 UTC, merged