fix url
collective/collective.documentgenerator pull request #53
Opened 2022-04-20 07:17 UTC by Arhell

2022-04-20 07:25 UTC, ale-rt requested changes

2022-04-20 07:25 UTC, ale-rt commented on README.rst
> +The `appy framework <http://appyframework.org>`_ is used to interpret the template and render it using the context.
```suggestion
The `appy framework <https://appyframe.work/tool/public>`_ is used to interpret the template and render it using the context.
```

2022-04-20 07:25 UTC, ale-rt commented on docs/user.rst
> +You can find a `documentation <http://appyframework.org/podWritingTemplates.html>`_ explaining the syntax that can be used.
```suggestion
You can find a `documentation <ttps://appyframe.work/13>`_ explaining the syntax that can be used.
```

2022-04-20 07:25 UTC, ale-rt commented on setup.py
> +    description="Desktop document generation (.odt, .pdf, .doc, ...) based on appy framework (http://appyframework.org) and OpenOffice/LibreOffice",
```suggestion
    description="Desktop document generation (.odt, .pdf, .doc, ...) based on appy framework (https://appyframe.work/tool/public) and OpenOffice/LibreOffice",
```

2022-04-21 09:17 UTC, Arhell commented on README.rst
> +The `appy framework <http://appyframework.org>`_ is used to interpret the template and render it using the context.
Done thanks

2022-04-21 09:17 UTC, Arhell commented on docs/user.rst
> +The `appy framework <http://appyframework.org>`_ is used to interpret the template and render it using the context.
Done thanks

2022-04-21 09:17 UTC, Arhell commented on docs/user.rst
> +You can find a `documentation <http://appyframework.org/podWritingTemplates.html>`_ explaining the syntax that can be used.
Done thanks

2022-04-21 09:17 UTC, Arhell commented on setup.py
> +    description="Desktop document generation (.odt, .pdf, .doc, ...) based on appy framework (http://appyframework.org) and OpenOffice/LibreOffice",
Done thanks

2022-04-21 21:29 UTC, merged